<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SiteInfo extends Model
{
    use HasFactory;

    protected $table = 'siteinfo';

    protected $fillable = [
        'google_location',
        'footer_google_location',
        'footer_contact_note',
        'maintenance_mode',
        'logo',
        'logo_width',
        'logo_height',
        'favicon',
        'favicon_width',
        'favicon_height',
        'buy_home_icon',
        'sell_home_icon',
        'rent_property_icon',
        'calculator_price_min',
        'calculator_price_max',
        'calculator_price_step',
        'calculator_default_price',
        'calculator_down_percent_min',
        'calculator_down_percent_max',
        'calculator_default_down_percent',
        'calculator_loan_year_min',
        'calculator_loan_year_max',
        'calculator_default_loan_years',
        'calculator_interest_min',
        'calculator_interest_max',
        'calculator_default_interest_rate',
        'calculator_tax_min',
        'calculator_tax_max',
        'calculator_default_tax_rate',
        'calculator_service_charge_min',
        'calculator_service_charge_max',
        'calculator_default_service_charge',
        'calculator_service_charge_step',
        'image_output_format',
        'contact_email',
        'enable_user_register',
        'phone_number_required',
        'enable_subscription_notify',
        'enable_save_contact_message',
        'text_direction',
        'default_theme',
        'timezone',
        'sidebar_lg_header',
        'sidebar_sm_header',
        'topbar_phone',
        'topbar_email',
        'currency_name',
        'currency_icon',
        'currency_rate',
        'default_phone_code',
        'frontend_url',
        'homepage_section_title',
        'slider_width',
        'slider_height',
        'about_image_width',
        'about_image_height',
        'property_image_width',
        'property_image_height',
        'blog_post_image_width',
        'blog_post_image_height',
        'blog_page_image_width',
        'blog_page_image_height',
        'agency_logo_width',
        'agency_logo_height',
        'seo_title',
        'seo_description',
        'meta_title',
        'meta_description',
        'meta_image',
        'author',
        'publisher',
        'copyright',
        'site_name',
        'keywords',
        'robots',
    ];

    protected $casts = [
        'maintenance_mode' => 'boolean',
        'enable_user_register' => 'boolean',
        'phone_number_required' => 'boolean',
        'enable_subscription_notify' => 'boolean',
        'enable_save_contact_message' => 'boolean',
        'currency_rate' => 'decimal:4',
        'logo_width' => 'integer',
        'logo_height' => 'integer',
        'favicon_width' => 'integer',
        'favicon_height' => 'integer',
        'slider_width' => 'integer',
        'slider_height' => 'integer',
        'about_image_width' => 'integer',
        'about_image_height' => 'integer',
        'property_image_width' => 'integer',
        'property_image_height' => 'integer',
        'blog_post_image_width' => 'integer',
        'blog_post_image_height' => 'integer',
        'blog_page_image_width' => 'integer',
        'blog_page_image_height' => 'integer',
        'agency_logo_width' => 'integer',
        'agency_logo_height' => 'integer',
        'calculator_price_min' => 'integer',
        'calculator_price_max' => 'integer',
        'calculator_price_step' => 'integer',
        'calculator_default_price' => 'integer',
        'calculator_down_percent_min' => 'integer',
        'calculator_down_percent_max' => 'integer',
        'calculator_default_down_percent' => 'integer',
        'calculator_loan_year_min' => 'integer',
        'calculator_loan_year_max' => 'integer',
        'calculator_default_loan_years' => 'integer',
        'calculator_interest_min' => 'decimal:2',
        'calculator_interest_max' => 'decimal:2',
        'calculator_default_interest_rate' => 'decimal:2',
        'calculator_tax_min' => 'decimal:2',
        'calculator_tax_max' => 'decimal:2',
        'calculator_default_tax_rate' => 'decimal:2',
        'calculator_service_charge_min' => 'integer',
        'calculator_service_charge_max' => 'integer',
        'calculator_default_service_charge' => 'integer',
        'calculator_service_charge_step' => 'integer',
    ];
}
